name = "bulk-find-replace"
compatibility_date = "2026-08-22"

# Tells Cloudflare Workers to serve the static assets from this directory
[assets]
directory = "./out"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
